// Resources/public/ts/ng/grid.component.ts
import {
    Component,
    Inject,
    Input,
    OnInit,
    AfterViewInit,
    ViewChild,
    ViewEncapsulation,
    ComponentFactory,
    ComponentRef,
    ComponentFactoryResolver,
    ViewContainerRef, ViewChildren, Directive, HostListener
} from '@angular/core';
import type { BazingaTranslator } from 'bazinga-translator';
import {Router} from '@angular/router';

declare var Translator: BazingaTranslator;
import {HttpClient} from '@angular/common/http';
import {AgGridAngular} from 'ag-grid-angular';

import("ag-grid-enterprise");
import {LicenseManager} from "ag-grid-enterprise";
import {StingerSoftAggrid} from "../StingerSoftAggrid";
import {GridConfiguration} from "../GridConfiguration";

LicenseManager.setLicenseKey("your license key");

@Component({
    selector: 'stinger-grid',
    templateUrl: './grid.component.html',
})
export class GridComponent implements OnInit, AfterViewInit {
    agGrid: AgGridAngular;

    @ViewChild('gridContainer', {read: ViewContainerRef}) entry: ViewContainerRef;

    @Input() src: string;

    configuration: any;

    stingerAggrid: StingerSoftAggrid;

    constructor(
        @Inject(HttpClient) private http: HttpClient,
        @Inject(ComponentFactoryResolver) private componentFactoryResolver: ComponentFactoryResolver,
        @Inject(Router) private router: Router
    ) {
    }

    fetchColumnDefs(url: string) {
        this.http.post<GridConfiguration>(url, {
            'agGrid': {
                'gridId': 1
            }
        }).subscribe((p) => {
            this.configuration = p;
            this.processConfiguration();
            this.createAggrid();
        });
    }

    ngAfterViewInit() {
        this.fetchColumnDefs(this.src);
    }

    ngOnInit(): void {

    }

    processConfiguration() {
        StingerSoftAggrid.processJsonConfiguration(this.configuration);
        console.log(this.configuration);
    }

    createAggrid(): void {
        const componentFactory = this.componentFactoryResolver.resolveComponentFactory(AgGridAngular);
        const componentRef = this.entry.createComponent(componentFactory);
        this.agGrid = componentRef.instance;
        componentRef.instance.gridOptions = this.configuration.aggrid;

        componentRef.instance.gridReady.subscribe((r) => {
            this.stingerAggrid = new StingerSoftAggrid(element, this.agGrid.api, this.agGrid.columnApi);
            this.stingerAggrid.init(this.configuration);
        });

        // getting the component's HTML
        let element: HTMLElement = <HTMLElement>componentRef.location.nativeElement;

        if (this.configuration.stinger.attr) {
            element.setAttribute('style', this.configuration.stinger.attr.style);
            element.classList.add(this.configuration.stinger.attr.class);
            element.id = this.configuration.stinger.attr.id;
        }
    }

    @HostListener('document:click', ['$event'])
    public handleClick(event: Event): void {
        if (event.target instanceof HTMLAnchorElement) {
            const element = event.target as HTMLAnchorElement;
            if (element.className === 'routerlink' && element?.hasAttribute('nghref')) {
                event.preventDefault();
                const route = element?.getAttribute('nghref');
                if (route) {
                    event.preventDefault();
                    this.router.navigate([`/${route}`]);
                }
            }
        }
    }
}
<div class="mb-1 aggrid-topbar">
    <input *ngIf="configuration?.stinger.searchEnabled" type="text" class="pull-left form-control input-small col-lg-3 col-xl-2  aggrid-quick-search"
           placeholder="{{ 'stingersoft_aggrid.searchOoo'|stinger_trans:{}: 'StingerSoftAggridBundle' }}"
           (input)="stingerAggrid?.quickFilter($event.target.value)" />
    <div class="col-lg-9 col-xl-10 aggrid-actions row">
        <div *ngIf="configuration?.aggrid.pagination && configuration?.stinger.paginationDropDown !== null && configuration?.stinger.paginationDropDown.length > 0" class="form-group row col-lg-1 col-xl-2 aggrid-entries-per-page">
            <label class="col-6 col-form-label">{{ 'stingersoft_aggrid.pagination.entries_per_page'|stinger_trans:{}: 'StingerSoftAggridBundle' }}</label>
            <div class="col-6">
                <select class="form-control input-xsmall" (change)="stingerAggrid?.setPaginationPageSize($event.target.value)">
                    <option
                            *ngFor="let entry of configuration?.stinger.paginationDropDown"
                            value="{{ entry }}"
                            [attr.selected]="entry == configuration?.aggrid.paginationPageSize ? true : null"
                    >
                        {{ entry }}
                    </option>
                    <option *ngIf="configuration?.stinger.paginationDropDown.indexOf(configuration?.aggrid.paginationPageSize) < 0" value="{{ configuration?.aggrid.paginationPageSize }}" selected="selected">{{ configuration?.aggrid.paginationPageSize }}</option>
                    <option value="999999999">{{ 'stingersoft_aggrid.selectAll'|stinger_trans:{}: 'StingerSoftAggridBundle' }}</option>
                </select>
            </div>
        </div>
        <div class="aggrid-action-buttons" *ngIf="configuration?.stinger.reloadButton || configuration?.stinger.clearFilterButton || configuration?.stinger.autosizeColumnsButton">
            <a href="javascript:void(0);" class="btn btn-default btn-icon aggrid-autosize"
               *ngIf="configuration?.stinger.autosizeColumnsButton"
               data-toggle="tooltip"
               (click)="stingerAggrid?.autoSizeColumns()"
               title="{{ 'stingersoft_aggrid.autosizeAllColumns'|stinger_trans:{}: 'StingerSoftAggridBundle' }}">
                <i class="far fa-fw fa-text-width"></i>
            </a>
            <a href="javascript:void(0);" class="btn btn-default btn-icon aggrid-reload"
               data-toggle="tooltip"
               *ngIf="configuration?.stinger.reloadButton"
               (click)="stingerAggrid?.reload()"
               title="{{ 'stingersoft_aggrid.refresh'|stinger_trans:{}: 'StingerSoftAggridBundle' }}">
                <i class="fas fa-fw fa-sync"></i>
            </a>
            <a href="javascript:void(0);" class="btn btn-default btn-icon aggrid-clear"
                data-toggle="tooltip"
               (click)="stingerAggrid?.resetFilter()"
               *ngIf="configuration?.stinger.clearFilterButton"
               title="{{ 'stingersoft_aggrid.clearFilter'|stinger_trans:{}: 'StingerSoftAggridBundle' }}">
                <i class="far fa-fw fa-trash"></i>
            </a>
        </div>
    </div>
</div>
<ng-template #gridContainer></ng-template>

// Resources/public/ts/react/GridComponent.tsx
import {AllCommunityModules} from "@ag-grid-community/all-modules";
import {AgGridReact} from "@ag-grid-community/react";
import React from "react";
import axios from 'axios';
import {StingerSoftAggrid} from 'stingersoftaggrid/ts/StingerSoftAggrid';
import {GridConfiguration} from 'stingersoftaggrid/ts/GridConfiguration';
import type { BazingaTranslator } from 'bazinga-translator';
import "./GridComponent.scss";
import { NavigateFunction } from "react-router-dom";

declare var Translator: BazingaTranslator;


interface IProps {
    src: string;
    translator?: BazingaTranslator;
    navigate?: NavigateFunction;
}

interface IState {
    configuration?: any;
    stingerAggrid?: StingerSoftAggrid;
    loading: boolean;
}

export class GridComponent extends React.Component<IProps, IState> {

    gridRef: React.RefObject<AgGridReact>;
    gridContainer: React.RefObject<HTMLDivElement>;

    translator: BazingaTranslator;
    navigate?: NavigateFunction;

    constructor(props) {
        super(props);
        this.translator = props.translator || global.Translator;
        this.navigate = props.navigate;
        this.gridRef = React.createRef<AgGridReact>();
        this.gridContainer = React.createRef<HTMLDivElement>();
        this.state = { configuration: null, stingerAggrid: null, loading: true }
        this.fetchColumnDefs(props.src);
        this.gridReadyListener = this.gridReadyListener.bind(this);
        this.handleClick = this.handleClick.bind(this);
    }


    fetchColumnDefs(url: string) {
        axios.post<GridConfiguration>(url, {
            'agGrid': {
                'gridId': 1
            }
        }).then((p) => {
            let configuration = p.data;
            configuration = this.processConfiguration(configuration);
            this.setState({ configuration: configuration, loading: false  });
        });
    }

    componentDidMount() {
    }

    gridReadyListener() {
        const agGrid = this.gridRef.current;
        // @ts-ignore
        const stingerAggrid = new StingerSoftAggrid(this.gridContainer.current, agGrid.api, agGrid.columnApi);
        stingerAggrid.init(this.state.configuration);
        this.setState({ stingerAggrid: stingerAggrid});
    }

    processConfiguration(configuration) {
        StingerSoftAggrid.processJsonConfiguration(configuration);
        return configuration;
    }

    /**
     * @function parseStyles
     * Parses a string of inline styles into a javascript object with casing for react
     *
     * @param {string} styles
     * @returns {Object}
     */
    parseStyles(styles: string): any {
        return styles
            .split(';')
            .filter(style => style.split(':')[0] && style.split(':')[1])
            .map(style => [
                style.split(':')[0].trim().replace(/-./g, c => c.substr(1).toUpperCase()),
                style.split(':')[1].trim()
            ])
            .reduce((styleObj, style) => ({
                ...styleObj,
                [style[0]]: style[1],
            }), {});
    }

    handleClick(event: Event): void {
        if (event.target instanceof HTMLAnchorElement) {
            const element = event.target as HTMLAnchorElement;
            if (element.className === 'routerlink' && element?.hasAttribute('reacthref') && this.navigate) {
                event.preventDefault();
                const route = element?.getAttribute('reacthref');
                if (route) {
                    event.preventDefault();
                    this.navigate(route);
                }
            }
        }
    }

    render() {
        if(this.state.loading) {
            return "";
        }

        const configuration = this.state.configuration;
        const stingerAggrid = this.state.stingerAggrid;
        if(configuration.stinger.attr && configuration.stinger.attr.hasOwnProperty('class')) {
            configuration.stinger.attr['className'] = configuration.stinger.attr['class'];
            delete configuration.stinger.attr['class'];
        }
        if(configuration.stinger.attr && configuration.stinger.attr.hasOwnProperty('style') && !(typeof configuration.stinger.attr['style'] === 'object' )) {
            configuration.stinger.attr['style'] = this.parseStyles(configuration.stinger.attr['style']);
        }

        return (<>
                <div>
                    <div className="mb-1 aggrid-topbar">
                        { configuration.stinger.searchEnabled &&
							<input type="text"
								   className="pull-left form-control input-small col-lg-3 col-xl-2  aggrid-quick-search"
								   placeholder={Translator.trans('stingersoft_aggrid.searchOoo', {}, 'StingerSoftAggridBundle')}
								   onChange={(e) => stingerAggrid?.quickFilter(e.target.value)} />
                        }

                        <div className="col-lg-9 col-xl-10 aggrid-actions row">
                            { configuration?.aggrid.pagination && configuration?.stinger.paginationDropDown !== null && configuration?.stinger.paginationDropDown.length > 0 &&
								<div className="form-group row col-lg-1 col-xl-2 aggrid-entries-per-page">
									<label className="col-6 col-form-label">{Translator.trans('stingersoft_aggrid.pagination.entries_per_page', {}, 'StingerSoftAggridBundle')}</label>
									<div className="col-6">
										<select className="form-control input-xsmall"  onChange={(e) => stingerAggrid?.setPaginationPageSize(e.target.value)}>
                                            { configuration?.stinger.paginationDropDown.map(entry =>
                                                <option selected={entry == configuration?.aggrid.paginationPageSize ? true : null} value={ entry }> { entry }</option>
                                            )}
                                            { configuration?.stinger.paginationDropDown.indexOf(configuration?.aggrid.paginationPageSize) < 0 &&  <option selected={true} value={ configuration?.aggrid.paginationPageSize }> { configuration?.aggrid.paginationPageSize }</option> }
											<option value="999999999">{ Translator.trans('stingersoft_aggrid.selectAll',{}, 'StingerSoftAggridBundle' )}</option>
										</select>
									</div>
								</div>
                            }
                            { (configuration?.stinger.reloadButton || configuration?.stinger.clearFilterButton || configuration?.stinger.autosizeColumnsButton) &&
								<div className="aggrid-action-buttons">
                                    {configuration?.stinger.autosizeColumnsButton &&
										<a href="" className="btn btn-default btn-icon aggrid-autosize"
										   data-toggle="tooltip"
										   onClick={(e) => {e.preventDefault(); stingerAggrid?.autoSizeColumns()} }
										   title={ Translator.trans('stingersoft_aggrid.autosizeAllColumns',{}, 'StingerSoftAggridBundle' )}>
											<i className="far fa-fw fa-text-width"></i>
										</a>
                                    }
                                    { configuration?.stinger.reloadButton &&
										<a href="" className="btn btn-default btn-icon aggrid-reload"
										   data-toggle="tooltip"
										   onClick={(e) => {e.preventDefault(); stingerAggrid?.reload(); } }
										   title={ Translator.trans('stingersoft_aggrid.refresh',{}, 'StingerSoftAggridBundle' )}>
											<i className="far fa-fw fa-sync"></i>
										</a>
                                    }
                                    { configuration?.stinger.clearFilterButton &&
										<a href="" className="btn btn-default btn-icon aggrid-clear"
										   data-toggle="tooltip"
										   onClick={(e) => {e.preventDefault(); stingerAggrid?.resetFilter(); } }
										   title={ Translator.trans('stingersoft_aggrid.clearFilter',{}, 'StingerSoftAggridBundle' )}>
											<i className="far fa-fw fa-trash"></i>
										</a>
                                    }
								</div>
                            }
                        </div>
                    </div>
                    <div
                        ref={this.gridContainer}
                        onClick={this.handleClick}
                        {...configuration.stinger.attr}
                    >
                        <AgGridReact
                            onGridReady={this.gridReadyListener}
                            modules={AllCommunityModules}
                            ref={this.gridRef}
                            rowData={[]}
                            columnDefs={this.state.configuration.aggrid.columnDefs}
                            gridOptions={this.state.configuration.aggrid}
                        ></AgGridReact>
                    </div>
                </div>
            </>
        );
    }
}
